# Debug mode
debug: 1 # true/false

# Sequence Config
sequence:
  command0: 
    time: -10
    run: init
    params: ''
  command1:
    time: -1
    run: ignitor
    params: true
  command2: 
    time: -0.5
    run: ignitorFuelValve
    params: true
  command3: 
    time: -0.2
    run: ignitorOxyValve
    params: true
  command4: 
    time: 0
    run: fuelValve
    params: true
  command5: 
    time: 0.1
    run: ignitor
    params: false
  command6: 
    time: 0.1
    run: ignitorOxyValve
    params: false
  command7: 
    time: 0.3
    run: ignitorFuelValve
    params: false
  command8: 
    time: 0.5
    run: oxyValve
    params: true
  command9: 
    time: 10
    run: end
    params: ''
 
# Devices
devices:
    0:
      name: "Temp"
      unit: "deg C"      
    1:
      name: "Kerosine Flow Rate"
      unit: "L/min"      
    2:
      name: "Kerosine Consumption"
      unit: "L"
      itegrate: 1 # device 1

# Outputs
outputs:
  ignitor: 0
  ignitorFuelValve: 1
  ignitorOxyValve: 2
  fuelValve: 3
  oxyValve: 4
  names:
    0: "Ignitor"
    1: "Ignitor Fuel Valve"
    2: "Ignitor Oxygen Valve"
    3: "Main Fuel Valve"
    4: "Main Oxygen Valve"

# Data log
log:
  folder: "logs/"
  appendDate: 0 # true/false
  extension: ".csv"

# Server Settings
server:
  port: 80
  
# I/O
serial:
  port: /dev/ttyAMA0
  baudrate: 9600