# Debug mode
debug: 0 # True/False

# Sequence Config
sequence:
  command0: 
    time: -10
    run: init
    params: ''
  command1:
    time: -1
    run: ignitor
    params: true
  command2: 
    time: 0
    run: ignitor
    params: false
  command3: 
    time: 0
    run: fuelValve
    params: true
  command4: 
    time: 0.5
    run: oxyValve
    params: true
  command5: 
    time: 10
    run: end
    params: ''
  
# Outputs
outputs:
  ignitor: 0
  fuelValve: 1
  oxyValve: 2

# Server Settings
server:
  port: 80
  
# I/O
serial:
  port: /dev/ttyAMA0 
  baudrate: 9600
  