# Debug mode
debug: 0 # True/False

# Sequence Config
sequence:
  command0: 
    time: -30
    run: init
    params: ''
  command1:
    time: -10
    run: ignitor
    params: true
  command2: 
    time: 0
    run: end
    params: ''
  starttime: -30 # seconds
  
# Server Settings
server:
  port: 80