# Debug mode
debug: 0 # true/false

# Sequence Config
sequence:
  command0: 
    time: -10
    run: init
    params: ''
  command1:
    time: -1
    run: ignitor
    params: true
  command2: 
    time: -0.5
    run: ignitorFuelValve
    params: true
  command3: 
    time: -0.2
    run: ignitorOxyValve
    params: true
  command4: 
    time: 0
    run: fuelValve
    params: true
  command5: 
    time: 0.1
    run: ignitor
    params: false
  command6: 
    time: 0.1
    run: ignitorOxyValve
    params: false
  command7: 
    time: 0.3
    run: ignitorFuelValve
    params: false
  command8: 
    time: 0.5
    run: oxyValve
    params: true
  command9: 
    time: 10
    run: end
    params: ''
  
# Outputs
outputs:
  ignitor: 0
  ignitorFuelValve: 1
  ignitorOxyValve: 2
  fuelValve: 3
  oxyValve: 4

# Data log
log:
  file: "logs/log"
  appendDate: 1 # true/false
  extension: null

# Server Settings
server:
  port: 80
  
# I/O
serial:
  port: /dev/ttyAMA0 
  baudrate: 9600
  