# ***EXAMPLE***

# Debug mode
debug: 0 # true/false

# Sequence Config
sequence: # Commands in numerical order
  command0: 
    time: -10  # in seconds
    run: init  # function to call
    params: '' # parameters to pass
  command1: 
    time: -0.5
    run: fuelValve
    params: true
  command2:
    time: 0
    run: ignitor
    params: true
  command3: 
    time: 0.5
    run: ignitor
    params: false
  command4: 
    time: 0.5
    run: oxyValve
    params: true
  command5: 
    time: 5.5
    run: end
    params: ''
 
# Devices
devices: # Analog Inputs in Numberical Order
    0:
      name: "Temp"
      unit: "deg C"      
    1:
      name: "Kerosine Flow Rate"
      unit: "L/sec"      
    2:
      name: "Kerosine Consumption"
      unit: "L"
      integrand: "1" # device 1
    3:
      name: "Temp Change"
      unit: "deg C/sec"
      derivativeOf: "0" # device 0

# Outputs
outputs:
  ignitor: 0
  fuelValve: 1
  oxyValve: 2
  names:
    0: "Ignitor"
    1: "Main Fuel Valve"
    2: "Main Oxygen Valve"

# Data log
log:
  folder: "logs/"
  appendDate: 0 # true/false
  extension: ".csv"

# Server Settings
server:
  port: 80
  
# I/O
serial:
  port: /dev/ttyAMA0
  baudrate: 9600
