# ***MAKER FAIRE***

# Debug mode
debug: 0 # true/false

# Sequence Config
sequence: # Commands in numerical order
  command0: 
    time: -10  # in seconds
    run: init  # function to call
    params: '' # parameters to pass
  command1:
    time: -6
    run: heliumValve
    params: true
  command2: 
    time: 0
    run: fuelValve
    params: true
  command3: 
    time: 7
    run: oxyValve
    params: true
  command4: 
    time: 12
    run: end
    params: ''
 
# Devices
devices: # Analog Inputs in Numberical Order
    0:
      name: "Temp"
      unit: "deg C"      
    1:
      name: "Kerosine Flow Rate"
      unit: "L/sec"      
    2:
      name: "Kerosine Consumption"
      unit: "L"
    3:
      name: "Temp Change"
      unit: "deg C/sec"
      derivativeOf: "0" # device 0

# Outputs
outputs:
  heliumValve: 0
  ignitor: 0
  ignitorFuelValve: 1
  ignitorOxyValve: 2
  fuelValve: 3
  oxyValve: 4
  names:
    0: "Ignitor"
    1: "Ignitor Fuel Valve"
    2: "Ignitor Oxygen Valve"
    3: "Main Fuel Valve"
    4: "Main Oxygen Valve"

# Data log
log:
  folder: "logs/"
  appendDate: 0 # true/false
  extension: ".csv"

# Server Settings
server:
  port: 80
  
# I/O
serial:
  port: /dev/ttyAMA0
  baudrate: 9600
