nameArry=["Engine Surface Thermocouple 1"...
"Engine Surface Thermocouple 2"...
"Engine Surface Thermocouple 3"...
"Engine Chamber Thermocouple"...
"Engine Chamber Pressure"...
"LOX Tank Pressure"...
"Fuel Tank Pressure"...
"LOX Tank Temperature"...
"Fuel Tank Temperature"...
"Thrust Load Cell 1"...
"Thrust Load Cell 2"...
"Fuel Tank Mass Load Cell"...
"LOX Tank Mass Load Cell"...
"Pneumatic Air Pressure"...
"Helium Pressure"...
"LOX Injector Pressure"...
"Fuel Injector Pressure"...
"Fuel Valve Opening Potentiometer"...
"Oxygen Valve Opening Potentiometer"...
"Fuel Valve Force"...
"LOX Valve Force"];

hold off
clf('reset')
[data text]=importdata("data/dat_115.csv");
x= str2double(data.textdata(:,1));
x=x-x(2);
len = 1;
b = ones(len,1)/len;
m = [6,16,5,15,11,12,17,18];
legNames = [];
rangeX = [70, 80];
fprintf("range: %.2f sec\n",rangeX(2)-rangeX(1));
for n = m
    col1 = data.data(:, n+1);
    I = ~isnan(col1) & ~isnan(x)& rangeX(1)<x & x<rangeX(2);
    hold on
    plot(x(I), filter(b,1,flip(filter(b,1,flip(col1(I))))) ,"-")
    fprintf("mean col %d: %.2f\n",n,mean(col1(I)));
    legNames=[legNames nameArry(n+1)];
end
axis tight

legend(legNames)